using System.Text;

namespace Terminal.Gui.Cli;

/// <summary>Strips dangerous terminal escape sequences from untrusted content.</summary>
public static class TerminalEscapeSanitizer
{
    /// <summary>Sanitizes user-supplied content before it reaches a terminal driver.</summary>
    public static string? Sanitize (string? input)
    {
        return input is null ? null : StripEscapes (input, false);
    }

    /// <summary>Sanitizes rendered ANSI, preserving only SGR CSI sequences generated by trusted renderers.</summary>
    public static string SanitizeRenderedOutput (string renderedAnsi)
    {
        ArgumentNullException.ThrowIfNull (renderedAnsi);
        return StripEscapes (renderedAnsi, true);
    }

    private static string StripEscapes (string input, bool preserveSgr)
    {
        StringBuilder output = new (input.Length);

        for (var i = 0; i < input.Length; i++)
        {
            var c = input[i];

            if (c != '\u001b')
            {
                output.Append (c);
                continue;
            }

            if (preserveSgr && TryReadSgr (input, i, out var endIndex))
            {
                output.Append (input, i, endIndex - i + 1);
                i = endIndex;
                continue;
            }

            i = SkipEscape (input, i);
        }

        return output.ToString ();
    }

    private static bool TryReadSgr (string input, int start, out int endIndex)
    {
        endIndex = start;

        if (start + 2 >= input.Length || input[start + 1] != '[')
        {
            return false;
        }

        var i = start + 2;

        while (i < input.Length && (char.IsDigit (input[i]) || input[i] == ';'))
        {
            i++;
        }

        if (i < input.Length && input[i] == 'm')
        {
            endIndex = i;
            return true;
        }

        return false;
    }

    private static int SkipEscape (string input, int start)
    {
        if (start + 1 >= input.Length)
        {
            return start;
        }

        var introducer = input[start + 1];

        if (introducer == '[')
        {
            for (var i = start + 2; i < input.Length; i++)
            {
                if (input[i] is >= '@' and <= '~')
                {
                    return i;
                }
            }

            return input.Length - 1;
        }

        if (introducer == ']')
        {
            for (var i = start + 2; i < input.Length; i++)
            {
                if (input[i] == '\u0007')
                {
                    return i;
                }

                if (input[i] == '\u001b' && i + 1 < input.Length && input[i + 1] == '\\')
                {
                    return i + 1;
                }
            }

            return input.Length - 1;
        }

        return start + 1;
    }
}
